sudo: required

services:
  - docker

language: ruby

rvm:
  - 1.9.3
  - 2.0.0

script:
 - make test-unit
 - bundle exec rake beaker

env:
  global:
    - LOGSTASH_VERSION=1.4.5
  matrix:
    - PUPPET_VERSION="3.0.2" BEAKER_set=debian-7
    - PUPPET_VERSION="3.1.1" BEAKER_set=debian-7
    - PUPPET_VERSION="3.2.4" BEAKER_set=debian-7
    - PUPPET_VERSION="3.3.2" BEAKER_set=debian-7
    - PUPPET_VERSION="3.4.3" BEAKER_set=debian-7
    - PUPPET_VERSION="3.5.1" BEAKER_set=debian-7
    - PUPPET_VERSION="3.6.2" BEAKER_set=debian-7
    - PUPPET_VERSION="3.7.5" BEAKER_set=debian-7
    - PUPPET_VERSION="3.8.6" BEAKER_set=debian-7

    - PUPPET_VERSION="3.0.2" BEAKER_set=debian-8
    - PUPPET_VERSION="3.1.1" BEAKER_set=debian-8
    - PUPPET_VERSION="3.2.4" BEAKER_set=debian-8
    - PUPPET_VERSION="3.3.2" BEAKER_set=debian-8
    - PUPPET_VERSION="3.4.3" BEAKER_set=debian-8
    - PUPPET_VERSION="3.5.1" BEAKER_set=debian-8
    - PUPPET_VERSION="3.6.2" BEAKER_set=debian-8
    - PUPPET_VERSION="3.7.5" BEAKER_set=debian-8
    - PUPPET_VERSION="3.8.6" BEAKER_set=debian-8

    - PUPPET_VERSION="3.0.2" BEAKER_set=centos-6
    - PUPPET_VERSION="3.1.1" BEAKER_set=centos-6
    - PUPPET_VERSION="3.2.4" BEAKER_set=centos-6
    - PUPPET_VERSION="3.3.2" BEAKER_set=centos-6
    - PUPPET_VERSION="3.4.3" BEAKER_set=centos-6
    - PUPPET_VERSION="3.5.1" BEAKER_set=centos-6
    - PUPPET_VERSION="3.6.2" BEAKER_set=centos-6
    - PUPPET_VERSION="3.7.5" BEAKER_set=centos-6
    - PUPPET_VERSION="3.8.6" BEAKER_set=centos-6

    - PUPPET_VERSION="3.0.2" BEAKER_set=centos-7
    - PUPPET_VERSION="3.1.1" BEAKER_set=centos-7
    - PUPPET_VERSION="3.2.4" BEAKER_set=centos-7
    - PUPPET_VERSION="3.3.2" BEAKER_set=centos-7
    - PUPPET_VERSION="3.4.3" BEAKER_set=centos-7
    - PUPPET_VERSION="3.5.1" BEAKER_set=centos-7
    - PUPPET_VERSION="3.6.2" BEAKER_set=centos-7
    - PUPPET_VERSION="3.7.5" BEAKER_set=centos-7
    - PUPPET_VERSION="3.8.6" BEAKER_set=centos-7

# Puppet < 3.4.3 fails on Ruby 2
# REF: https://github.com/puppetlabs/puppet/commit/d02820a116d5e3ae0b129a0b4384ddaf76f0f83b
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="3.2.4" LOGSTASH_VERSION=1.4.5 BEAKER_set=debian-7
    - rvm: 2.0.0
      env: PUPPET_VERSION="3.3.2" LOGSTASH_VERSION=1.4.5 BEAKER_set=debian-7
  # 2016-04-18: All Ruby 1.9 builds are currently failing due to google-api-client
  # versioning.
  # REF: https://github.com/google/google-api-ruby-client/issues/397
  allow_failures:
    - rvm: 1.9.3
  fast_finish: true
